### ISSUE TITLE
proxy has crash messages.

### ISSUE THREAD

**Issue by danieldin95** [luscis/openlan#67]
```

goroutine 6183 [chan receive]:
github.com/luscis/openlan/pkg/libol.(*WaitOne).Wait(...)
	/opt/openlan/pkg/libol/wait.go:18
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).toTunnel(0xc0001a6870, 0x1524ac0, 0xc0008b4000, 0x1528558, 0xc00018e018)
	/opt/openlan/pkg/proxy/http.go:229 +0x266
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).ServeHTTP(0xc0001a6870, 0x1524ac0, 0xc0008b4000, 0xc0004fe100)
	/opt/openlan/pkg/proxy/http.go:368 +0x947
net/http.serverHandler.ServeHTTP(0xc0003a2000, 0x1524ac0, 0xc0008b4000, 0xc0004fe100)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00019c280, 0x15253e0, 0xc00049e000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b

goroutine 6078 [chan receive, 3 minutes]:
github.com/luscis/openlan/pkg/libol.(*WaitOne).Wait(...)
	/opt/openlan/pkg/libol/wait.go:18
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).toTunnel(0xc0001a6870, 0x1524ac0, 0xc0003a2700, 0x1528558, 0xc000714608)
	/opt/openlan/pkg/proxy/http.go:229 +0x266
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).ServeHTTP(0xc0001a6870, 0x1524ac0, 0xc0003a2700, 0xc000462400)
	/opt/openlan/pkg/proxy/http.go:356 +0x518
net/http.serverHandler.ServeHTTP(0xc0003a2000, 0x1524ac0, 0xc0003a2700, 0xc000462400)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0004400a0, 0x15253e0, 0xc000a10000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by danieldin95** [comment]
```
goroutine 137 [runnable]:
regexp.(*inputString).step(0xc000664130, 0xf, 0x7500000000, 0x1)
	/usr/local/go/src/regexp/regexp.go:383 +0xbf
regexp.(*Regexp).tryBacktrack(0xc0005c3ae0, 0xc0006640b0, 0x1526458, 0xc000664130, 0xc000000001, 0xf, 0xc0005ae900)
	/usr/local/go/src/regexp/backtrack.go:218 +0xb89
regexp.(*Regexp).backtrack(0xc0005c3ae0, 0x0, 0x0, 0x0, 0xc000322de7, 0x21, 0xf, 0x0, 0x1787e60, 0x0, ...)
	/usr/local/go/src/regexp/backtrack.go:353 +0x3af
regexp.(*Regexp).doExecute(0xc0005c3ae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000322de7, 0x21, 0x0, 0x0, ...)
	/usr/local/go/src/regexp/exec.go:535 +0x45c
regexp.(*Regexp).doMatch(...)
	/usr/local/go/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
	/usr/local/go/src/regexp/regexp.go:525
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).isMatch(0xc00006c8c0, 0xc000322de7, 0x21, 0xc00002ec40, 0x3, 0x4, 0xc0004f05a0)
	/opt/openlan/pkg/proxy/http.go:300 +0x16f
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).findForward(0xc00006c8c0, 0xc00022c700, 0xc00032e0e0)
	/opt/openlan/pkg/proxy/http.go:313 +0xaf
github.com/luscis/openlan/pkg/proxy.(*HttpProxy).ServeHTTP(0xc00006c8c0, 0x1524ac0, 0xc00032e0e0, 0xc00022c700)
	/opt/openlan/pkg/proxy/http.go:342 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000572000, 0x1524ac0, 0xc00032e0e0, 0xc00022c700)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0005c3860, 0x15253e0, 0xc00021efc0)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by danieldin95** [comment]
```
fatal error: concurrent map writes
fatal error: concurrent map writes

```
